### PR TITLE
Improves documentation for hacker_news_pwa

### PR DESCRIPTION
**Pull request by exo-pla-net**
This is an important example, since it illustrates the cutting edge of AngularDart and PWA's. With improved documentation, the example is a little more accessible to people new to AngularDart and Firebase.

### CODE REVIEW

**Comment by matanlurey** [comment]
Can we base this off of https://github.com/dart-lang/angular/pull/924?

**Comment by matanlurey** [comment]
Do you mind rebasing @exo-pla-net?

**Comment by exo-pla-net** [comment]
Hmm. I endeavored to do so, but the results appear somewhat disastrous.

**Comment by matanlurey** [comment]
Closing in favor of https://github.com/dart-lang/angular/pull/947.

**Pull request closed without merging**
