### PR TITLE
Verify travis fixes

### PR DESCRIPTION
**Pull request by alorenzen**
** DO NOT MERGE** 
This is just to verify travis fixes.

### CODE REVIEW

**Comment by kevmoo** [comment]
Can this PR be killed?

**Comment by alorenzen** [comment]
When the tests are running properly with build_runner on travis, then yes. But we are not there yet...

**Comment by kevmoo** [comment]
can we drop the -dev.6.0 platform? Will make things run faster...

**Comment by alorenzen** [comment]
This is just a PR for hacking, not something we intent to land. I really don't care how long it takes, as long as it actually gives us a useful signal.
I'm not really keeping this in a pristine state. Just throwing something out there for Jake to hack on...

**Pull request closed without merging**
