### PR TITLE
Add website verification for Google Web Master Tools

### PR DESCRIPTION
**Pull request by kevmoo**
A no-cost way to get some link stats

### CODE REVIEW

**Comment by leonsenft** [comment]
For someone like myself who has no idea what this is or does, mind providing some context please?

**Comment by kevmoo** [comment]
See https://support.google.com/webmasters/answer/35179?hl=en

This let's us tell webmaster tools that we own the site – so we can see search data, etc.

**Comment by leonsenft** [comment]
Thanks!

**Comment by matanlurey** [comment]
@kevmoo Do you mind syncing your own PRs?

**Comment by kevmoo** [comment]
I can if that's the process....

**Comment by kevmoo** [comment]
@leonsenft already merged this it seems...

**Comment by matanlurey** [comment]
Ah, yes, will be closed by https://github.com/dart-lang/angular/pull/1268.

**Pull request closed without merging**
