### PR TITLE
GitHub Sync

### PR DESCRIPTION
**Pull request by alorenzen**
This is an automatically generated pull request.

Closes https://github.com/dart-lang/angular/issues/1328.

### CODE REVIEW

**Comment by kevmoo** [comment]
Gah! one failed test!

**Comment by leonsenft** [comment]
We need to hold publishing this release until we bump the lower bound on csslib (which is waiting on the updating landing internally). I'll let you know when it's done.

**Comment by leonsenft** [comment]
Test failure due to inference change: https://github.com/dart-lang/sdk/issues/36777

**Comment by alorenzen** [comment]
This PR is getting large enough, I'd like to merge on red and continue to follow up with the Dart team on the test failure.

**Comment by leonsenft** [comment]
I'm fine with that, especially considering the failure can't be reproduced locally.

**Comment by alorenzen** [comment]
I need an LGTM on the PR to merge on red

**Comment by leonsenft** [comment]
Ah so it is reproducible locally, you just need to run the PR itself, not on master.

**Pull request merged**
