### PR TITLE
docs(Readme): fix logo

### LINKED ISSUE #1791: Fix logo in readme
May have to copy the image to this repo

### PR DESCRIPTION
**Pull request by jesselpalmer**
Closes #1791 /cc @kevmoo @benhalverson

### CODE REVIEW

**Comment by jesselpalmer** [comment]
Hello @matanlurey @alorenzen! Is there any way to get this merged? The PR is super small and it appears as though the logo on the README file is still broken. Thank you!

**Comment by jesselpalmer** [comment]
woohoo! thanks, @leonsenft! just in time for Hacktoberfest :-)

**Comment by jesselpalmer** [comment]
oh wow, i just relized @kwalrath is on this thread. you helped me with a PR almost 5 years ago: https://github.com/dart-archive/www.dartlang.org/pull/1145. nice crossing paths again.

**Comment by kwalrath** [comment]
> oh wow, i just relized @kwalrath is on this thread. you helped me with a PR almost 5 years ago: [dart-archive/www.dartlang.org#1145](https://github.com/dart-archive/www.dartlang.org/pull/1145). nice crossing paths again.

Oh hey, nice to see you again! :D

**Pull request closed without merging**
