### PR TITLE
angular_router 2: fix to JsObject has no getter 'queryParameters' issue

### LINKED ISSUE #654: angular_router 2: JsObject has no instance getter 'queryParameters' when testing
I'm getting the same exception as reported in #635, but this time under **Chrome** when running tests using angular_router 2.0.0-alpha (Dart 1.24.2, Angular 4.0.0). I'll post a link to the tests soon.

Here is the exception:
```nocode
00:01 +0 -11: test/all_test.dart: app: Deep linking: navigate to heroes [E]
Unhandled exception:
NoSuchMethodError: Class 'JsObject' has no instance getter 'queryParameters'.
Receiver: Instance of 'JsObject'
Tried calling: queryParameters
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      new _RouterJs.<anonymous closure> (package:angular_router/src/router/router_coordinator.dart:86:57)
#3      JsObject._callMethodLegacy (dart:js:1282)
#4      JsObject.callMethod (dart:js:1271)
#5      _RouterJs.navigate (package:angular_router/src/router/router_coordinator.dart:102:15)
#6      RouterCoordinator.navigate (package:angular_router/src/router/router_coordinator.dart:50:14)
<asynchronous suspension>
#7      RouterImpl.navigate (package:angular_router/src/router/router_impl.dart:106:39)
#8      RouterImpl.navigateRouter (package:angular_router/src/router/router_impl.dart:151:14)
<asynchronous suspension>
#9      RouterImpl.registerRootOutlet (package:angular_router/src/router/router_impl.dart:81:7)
#10     RouterOutlet.ngOnInit (package:angular_router/src/directives/router_outlet_directive.dart:93:31)
#11     ViewAppComponent0.detectChangesInternal (package:angular_tour_of_heroes/app_component.template.dart:180:26)
...
```

cc @kwalrath @alorenzen

### PR DESCRIPTION
**Pull request by chalin**
Fixes #654, and possibly #635 too. (I haven't ran the main angular_router tests so I don't know if they are impacted by this.)

cc @kwalrath @alorenzen

### CODE REVIEW

**Comment by zoechi** [comment]
Would the `getProperty` from https://github.com/dart-lang/sdk/blob/master/sdk/lib/js_util/dart2js/js_util_dart2js.dart#L62 (exported by `package:js/js_util.dart`) do the same as the one in the changed file?

**Comment by chalin** [comment]
Yes, thanks @zoechi! (In fact the return type was wrong on that local get prop method signature, so dropping it fixed that too :).

**Comment by matanlurey** [comment]
Sorry this took so long.

Is this only a bug for Dartium @chalin?

I'd be worried about adding a bug fix for a browser we'll delete before 5.x ever lands.

**Comment by chalin** [comment]
No, this happens under Chrome too; see _angular_router 2: JsObject has no instance getter 'queryParameters' when testing_ #654

**Comment by chalin** [comment]
Any updates on this? Btw, with this fix I can get the toh-5 component tests successfully passing once again (under Dart 2-dev, and Angular 5-alpha).

**Comment by leonsenft** [comment]
Thanks @chalin for looking into this and providing a fix. We're actually considering moving the `RouterCoordinator` out of this package altogether. We'd like to keep the default router implementation as lightweight as possible, but make it extensible so that a cross-shard router implementation could be maintained by those who need one. I'll follow up on this comment shortly to confirm this approach.

**Comment by leonsenft** [comment]
We have a fix for this internally that should by in the next sync.

**Comment by chalin** [comment]
Looking forward to it!

**Pull request closed without merging**
