### PR TITLE
GitHub sync

### PR DESCRIPTION
**Pull request by alorenzen**

### CODE REVIEW

**Comment by matanlurey** [comment]
@alorenzen We should probably blacklist the source_gen golden tests :-/

**Comment by alorenzen** [comment]
This actually looks like a legit failure to me. The golden files are not actually importing angular/angular.template.dart.

**Comment by alorenzen** [comment]
OK, I found the issue with the golden files. When we made usePlaceholder the default again, we didn't change it for the generate.dart script (literally the one place that it's intended to not use the default :stuck_out_tongue: )

It's an easy enough fix, so we can include it in this PR.

**Comment by matanlurey** [comment]
Great!

**Comment by matanlurey** [comment]
@alorenzen We need to ignore dartfmt for dev, otherwise LGTM.

**Pull request merged**
