### PR TITLE
Update to use published build package dependencies

### PR DESCRIPTION
**Pull request by jakemac53**
update to point at the latest master for package build (if this passes then we will publish and I will update to point at the published versions)

### CODE REVIEW

**Comment by jakemac53** [comment]
Looks like this is failing due to the same chrome issue we have been seeing, everything passes locally though.

**Comment by jakemac53** [comment]
This is now ready for review @alorenzen @matanlurey

**Comment by matanlurey** [comment]
LGTM. I'll merge this internally.

**Comment by jakemac53** [comment]
ok great @matanlurey

**Pull request closed without merging**
