### PR TITLE
GitHub Sync

### PR DESCRIPTION
**Pull request by kevmoo**
This is an automatically generated pull request.

### CODE REVIEW

**Comment by bogatkod** [comment]
Is there any progress?  We really need a new version of AngularDart)

**Comment by edyu** [comment]
Is this just waiting for CLA for commit authors? If so, can the commit authors please do so?

**Comment by DartViet** [comment]
please keep going, A framework going 8 months without any update makes me worried. Thanks for working hard behind scene. Let's open a donation on Angular Dart website so people can give you guys a hand.

**Comment by MitaiGit** [comment]
there's probably a lot of good stuff in there, when, when you roll it???

**Pull request closed without merging**
