### PR TITLE
Use mono repo again for travis 

### PR DESCRIPTION
**Pull request by jakemac53**
Replace .travis.yml files with .mono_repo.yml files, and use the generated .travis.yml and travis.sh scripts.

### CODE REVIEW

**Comment by matanlurey** [comment]
Nice. I'll merge on green.

**Comment by matanlurey** [comment]
Hmm... Did Chrome change, or is this a flake? @jakemac53

**Comment by jakemac53** [comment]
@matanlurey restarting the task to see

**Comment by jakemac53** [comment]
It seems like a legit failure... not sure how this cl could have caused it though?

**Comment by matanlurey** [comment]
Hmm. I'll pull it in, maybe this is transient.

**Comment by matanlurey** [comment]
@jakemac53 Going to try locally; maybe Chrome updated?

**Comment by matanlurey** [comment]
@jakemac53 I think we haven't been running most of our tests for a while on accident and now we are running more, or something like that. Investigating.

**Comment by jakemac53** [comment]
> @jakemac53 I think we haven't been running most of our tests for a while on accident and now we are running more, or something like that. Investigating.

Interesting, it was not my intention to change what tests run at all with this PR, but I could have made a mistake.

**Comment by matanlurey** [comment]
It's all good. I'm going to see if @leonsenft can fix or disable this specific 1 test, and then we'll merge this. Sorry for the delay.

**Pull request closed without merging**
